import { Person } from './types';

export const MOCK_PEOPLE: Person[] = [
  {
    id: 'arvin',
    name: 'Arvin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arvin',
    tasks: [
      {
        id: '1',
        type: 'Feature',
        status: 'In Progress',
        project: 'Bizpro',
        title: '我是issue標題~~~',
        issueNumber: '12345',
        createdAt: '2026/03/25',
        completedAt: '2026/04/01',
        author: 'Wang',
        updatedAt: '03/31 15:30',
      },
      {
        id: '2',
        type: 'Bug',
        status: 'New',
        project: 'Bizpro',
        title: '修正登入錯誤問題',
        issueNumber: '12346',
        createdAt: '2026/03/20',
        completedAt: '2026/03/31',
        author: 'Emma',
        updatedAt: '03/30 10:15',
      },
      {
        id: '3',
        type: 'Support',
        status: 'Resolved',
        project: 'WebApp',
        title: '客戶需求諮詢',
        issueNumber: '10685',
        createdAt: '2026/03/15',
        completedAt: '2026/03/30',
        author: 'Jason',
        updatedAt: '03/29 14:20',
      },
    ],
  },
  {
    id: 'emma',
    name: 'Emma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    tasks: [
      {
        id: '4',
        type: 'Test',
        status: 'In Progress',
        project: 'Bizpro',
        title: '單元測試覆蓋率提升',
        issueNumber: '12349',
        createdAt: '2026/03/18',
        completedAt: '2026/03/28',
        author: 'Wang',
        updatedAt: '03/31 11:20',
      },
      {
        id: '5',
        type: 'Optimization',
        status: 'Feedback',
        project: 'Bizpro',
        title: '優化資料庫查詢效能',
        issueNumber: '12347',
        createdAt: '2026/03/28',
        completedAt: '2026/04/05',
        author: 'Lily',
        updatedAt: '03/31 09:45',
      },
      {
        id: '6',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
       {
        id: '7',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
       {
        id: '8',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
       {
        id: '9',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
       {
        id: '10',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
    ],
  },
  {
    id: 'jason',
    name: 'Jason',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jason',
    tasks: [
      {
        id: '7',
        type: 'Bug',
        status: 'Rejected',
        project: 'Bizpro',
        title: '前端頁面顯示異常',
        issueNumber: '12351',
        createdAt: '2026/03/24',
        completedAt: '2026/03/30',
        author: 'Jason',
        updatedAt: '03/31 08:15',
      },
      {
        id: '8',
        type: 'Feature',
        status: 'Pause',
        project: 'Bizpro',
        title: '新功能開發需求',
        issueNumber: '12350',
        createdAt: '2026/03/26',
        completedAt: '2026/04/02',
        author: 'Emma',
        updatedAt: '03/30 17:30',
      },
    ],
  },
  {
    id: 'lily',
    name: 'Lily',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    tasks: [
      {
        id: '9',
        type: 'Conference',
        status: 'Resolved',
        project: 'Bizpro',
        title: '技術會議討論事項',
        issueNumber: '12354',
        createdAt: '2026/03/21',
        completedAt: '2026/03/27',
        author: 'Wang',
        updatedAt: '03/26 18:10',
      },
      {
        id: '10',
        type: 'Support',
        status: 'New',
        project: 'Bizpro',
        title: '待確認規格需求',
        issueNumber: '12352',
        createdAt: '2026/03/29',
        completedAt: '2026/04/06',
        author: 'Lily',
        updatedAt: '03/31 13:40',
      },
      {
        id: '11',
        type: 'Sales',
        status: 'In Progress',
        project: 'Bizpro',
        title: '業務專案討論',
        issueNumber: '12353',
        createdAt: '2026/03/27',
        completedAt: '2026/04/03',
        author: 'Lin',
        updatedAt: '03/30 12:50',
      },
    ],
  },
];
