import { Person } from './types';

export const MOCK_PEOPLE: Person[] = [
  {
    id: 'arvin',
    name: 'Arvin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arvin',
    tasks: [
      {
        id: '1',
        type: 'Feature',
        status: 'In Progress',
        project: 'Bizpro',
        title: '我是issue標題~~~',
        issueNumber: '12345',
        createdAt: '2026/03/25',
        completedAt: '2026/04/01',
        author: 'Wang',
        updatedAt: '03/31 15:30',
      },
      {
        id: '2',
        type: 'Bug',
        status: 'New',
        project: 'Bizpro',
        title: '修正登入錯誤問題',
        issueNumber: '12346',
        createdAt: '2026/03/20',
        completedAt: '2026/03/31',
        author: 'Emma',
        updatedAt: '03/30 10:15',
      },
      {
        id: '3',
        type: 'Support',
        status: 'Resolved',
        project: 'WebApp',
        title: '客戶需求諮詢',
        issueNumber: '10685',
        createdAt: '2026/03/15',
        completedAt: '2026/03/30',
        author: 'Jason',
        updatedAt: '03/29 14:20',
      },
    ],
  },
  {
    id: 'emma',
    name: 'Emma',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    tasks: [
      {
        id: '4',
        type: 'Test',
        status: 'In Progress',
        project: 'Bizpro',
        title: '單元測試覆蓋率提升',
        issueNumber: '12349',
        createdAt: '2026/03/18',
        completedAt: '2026/03/28',
        author: 'Wang',
        updatedAt: '03/31 11:20',
      },
      {
        id: '5',
        type: 'Optimization',
        status: 'Feedback',
        project: 'Bizpro',
        title: '優化資料庫查詢效能',
        issueNumber: '12347',
        createdAt: '2026/03/28',
        completedAt: '2026/04/05',
        author: 'Lily',
        updatedAt: '03/31 09:45',
      },
      {
        id: '6',
        type: 'Maintain',
        status: 'Closed',
        project: 'Bizpro',
        title: '系統例行維護',
        issueNumber: '12348',
        createdAt: '2026/03/22',
        completedAt: '2026/03/29',
        author: 'Lin',
        updatedAt: '03/28 16:00',
      },
      {
        id: '12',
        type: 'Feature',
        status: 'New',
        project: 'Bizpro',
        title: '開發 API 文件',
        issueNumber: '12355',
        createdAt: '2026/03/30',
        completedAt: '2026/04/07',
        author: 'Emma',
        updatedAt: '04/01 09:00',
      },
      {
        id: '13',
        type: 'Bug',
        status: 'In Progress',
        project: 'WebApp',
        title: '修復行動版選單問題',
        issueNumber: '12356',
        createdAt: '2026/03/31',
        completedAt: '2026/04/08',
        author: 'Arvin',
        updatedAt: '04/02 14:30',
      },
    ],
  },
  {
    id: 'jason',
    name: 'Jason',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jason',
    tasks: [
      {
        id: '7',
        type: 'Bug',
        status: 'Rejected',
        project: 'Bizpro',
        title: '前端頁面顯示異常',
        issueNumber: '12351',
        createdAt: '2026/03/24',
        completedAt: '2026/03/30',
        author: 'Jason',
        updatedAt: '03/31 08:15',
      },
      {
        id: '8',
        type: 'Feature',
        status: 'Pause',
        project: 'Bizpro',
        title: '新功能開發需求',
        issueNumber: '12350',
        createdAt: '2026/03/26',
        completedAt: '2026/04/02',
        author: 'Emma',
        updatedAt: '03/30 17:30',
      },
      {
        id: '14',
        type: 'Support',
        status: 'New',
        project: 'WebApp',
        title: '協助客戶匯出報表',
        issueNumber: '12357',
        createdAt: '2026/04/01',
        completedAt: '2026/04/05',
        author: 'Jason',
        updatedAt: '04/02 10:00',
      },
      {
        id: '15',
        type: 'Optimization',
        status: 'In Progress',
        project: 'Bizpro',
        title: '前端渲染效能優化',
        issueNumber: '12358',
        createdAt: '2026/04/02',
        completedAt: '2026/04/10',
        author: 'Lily',
        updatedAt: '04/03 11:00',
      },
      {
        id: '16',
        type: 'Maintain',
        status: 'New',
        project: 'Bizpro',
        title: '伺服器安全性更新',
        issueNumber: '12359',
        createdAt: '2026/04/03',
        completedAt: '2026/04/06',
        author: 'Lin',
        updatedAt: '04/03 15:00',
      },
      {
        id: '17',
        type: 'Feature',
        status: 'New',
        project: 'WebApp',
        title: '整合第三方支付',
        issueNumber: '12360',
        createdAt: '2026/04/04',
        completedAt: '2026/04/15',
        author: 'Arvin',
        updatedAt: '04/04 16:00',
      },
      {
        id: '18',
        type: 'Bug',
        status: 'In Progress',
        project: 'Bizpro',
        title: '修復權限控管漏洞',
        issueNumber: '12361',
        createdAt: '2026/04/05',
        completedAt: '2026/04/12',
        author: 'Emma',
        updatedAt: '04/06 09:30',
      },
      {
        id: '19',
        type: 'Test',
        status: 'New',
        project: 'WebApp',
        title: '自動化測試腳本撰寫',
        issueNumber: '12362',
        createdAt: '2026/04/05',
        completedAt: '2026/04/14',
        author: 'Jason',
        updatedAt: '04/06 13:00',
      },
      {
        id: '20',
        type: 'Conference',
        status: 'New',
        project: 'Bizpro',
        title: '季度技術回顧會議',
        issueNumber: '12363',
        createdAt: '2026/04/06',
        completedAt: '2026/04/06',
        author: 'Wang',
        updatedAt: '04/06 17:00',
      },
      {
        id: '21',
        type: 'Support',
        status: 'In Progress',
        project: 'Bizpro',
        title: '處理緊急線上問題',
        issueNumber: '12364',
        createdAt: '2026/04/07',
        completedAt: '2026/04/07',
        author: 'Jason',
        updatedAt: '04/07 08:30',
      },
    ],
  },
  {
    id: 'lily',
    name: 'Lily',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    tasks: [
      {
        id: '9',
        type: 'Conference',
        status: 'Resolved',
        project: 'Bizpro',
        title: '技術會議討論事項',
        issueNumber: '12354',
        createdAt: '2026/03/21',
        completedAt: '2026/03/27',
        author: 'Wang',
        updatedAt: '03/26 18:10',
      },
    ],
  },
];
